services:
  - type: web
    name: job-portal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python index.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
